var POMPEII_LEVEL = [
  ["                                                                                                ",
   "                                                                                                ",
   "                                                                                                ",
   "                                                                                                ",
   "                                                                                                ",
   "                                                                                                ",
   "                                                                                                ",
   "                                                                                                ",
   "                                                                                                ",
   "                                                                                                ",
   "                                                                                                ",
   "                                                                                                ",
   "                                                                                                ",
   "                                                                                                ",
   "                                                                                                ",
   "                                                                                                ",
   "                                                                                                ",
   "                                                                                                ",
   "                                                                                                ",
   "               a  a      a      a  a                                                            ",
   "                                                                                                ",
   "               xxxxx    xxx    xxxxx                                                            ",
   "                                                                                                ",
   "                                                                                                ",
   "  @      M       b               b                     b                                        ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                a  a               ",
   "                                                                                              xxxxxxxx             ",
   "                                                                               a   a     x                         ",
   "                                                                             xxxxxxxxx                             ",
   "                                                                       x                                           ",
   "                                                                                                                   ",
   "                                                                xxxxx                           xxxxxxxxx          ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                 a a         a       xxxxxx                                        ",
   "                                                xxxxx       xxx                                                    ",
   "                                                                                                                   ",
   "                                                                                                                   ",  
   "   @                         b            b       h          h          h          h                               ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                            ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                            ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                        ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                        ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                   ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                   ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                   ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx              ",  //M is a special key that
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx           M   W   ",  // # trigger an alert
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                    V              ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                  cccccc           ",
   "                                                                                                  cccccc           ",
   "                                                                                                  cccccc           ",
   "   # @                b                  b                  b                 b                   ccCCcc           ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["                                                                                                                                ",
   "                                                                                                                                ",
   "                                                                                                                                ",
   "                                                                                                                                ",
   "                                                                                                                                ",
   "                                                                                                                                ",
   "                                                                                                                                ",
   "                                                                                                                                ",
   "                                                                                                                                ",
   "                                                                                                                                ",
   "                                                                                                                                ",
   "                                                                                                                                ",
   "                                                                                                                                ",
   "                                                                                                                                ",
   "                                                                                                                                ",
   "                                                                                                                                ",
   "                                                                                                                                ",
   "                                                                                                                                ",
   "                                                                                                                                ",
   "                                                                                                                                ",
   "                                                                                                                            V   ",
   "                                                                                                                                ",
   "                              N                                                                                                 ",
   "                         xxxxxxxxxxxxxxxxxxx      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                           ",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                           ",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                     ",
   "                                                xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                     ",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                              ",
   "        xxxxxxxxxxx                       x       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxx                    ",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx              A  A            ",
   "                                              xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx             xxxxxx           ",
   "  A                                               xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                              ",
   "       b       b                           N      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                         @ #  ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["                                                                                                                                          ",
   "                                                                                                                                          ",
   "                                                                                                                                          ",
   "                                                                                                                                          ",
   "                                                                                                                                          ",
   "                                                                                                                                          ",
   "                                                                                                                                          ",
   "                                                                                                                                          ",
   "                                                                                                                                          ",
   "                                                                                                                                          ",
   "                                                                                                                                          ",
   "                                                                                                                                          ",
   "                                                                                                                                          ",
   "                                                                                                                                          ",
   "                                                                                                                                          ",
   "                                                                                                                                          ",
   "                                                                                                                                          ",
   "                                                                                                                                          ",
   "                                                                                                                                          ",
   "                                                                                                                                          ",
   "                                                                                                                                          ",
   "                                                                                                                                          ",
   "                                                                                                                                          ",
   "                                                                                                                                          ",
   "                                                                                                                                          ",
   "                                                                                                                                       V  ",
   "                N       A                                                                                                                 ",
   "              xxxxx          xxxx      xxxx         xxxxx                                                                                 ",
   "                                                                                                                                          ",
   "                                                               xxxxx                                                                      ",
   "                                                                                                                                          ",
   "                            A      N     A                                                                      A        A        A       ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                              xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   A                       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                              -                     ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    A    A                    -                     ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                -                     ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     A   A      -                @ #  ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                              V    ",
   "   A A A                                                                                                           ",
   " xxxxxxxxxx                                                                     A                                  ",
   "                                                                            A      A                               ",
   "                                                                         A            A                            ",
   "             b        A       A       A      A       A       A        A                  A      A            @ #   ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                V  ",
   "                                    N                      N                                                       ",
   "                              xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                        ",
   "                                                                                     N                             ",
   "                                                                                  xxxxxxxx                         ",
   "             xxxxxxx                                                                                               ",
   "                                                                                              xxxxxx               ",
   "                                                                                                                   ",
   "      N             N                               N              N                                         @ #   ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                      N           N                                                                             V  ",
   "                xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                     ",
   "                                                                                                                   ",
   "                                                                   xxxxxx                                          ",
   "                                                                                                                   ",
   "                                                          xxxx                                                     ",
   "                                                                                                                   ",
   "  N      N         N   N           N       N                                    N         b            b      @ #  ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                              V    ",
   "                                                                                                                   ",
   "           N              N              N     N            N                               N            N         ",
   "     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx          xxxxxxxxxxxxxxxxxxxxxxxxxxxxx    ",
   "                                                                       x                                           ",
   "                                                                       xxxxx                                       ",
   "                                                                                                                   ",
   "     N          N                 b                  N                                  b                   @ #    ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                               V   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                        N     N                    b       b               h           h           h          @ #  ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "           !!                                                                                                      ",
   "          !!!!!                                                                                                    ",
   "         !!!!!!!!                                                                                                  ",
   "       !!!!!!!!!                                                                                                   ",
   "      !!!!!!!!!!!!!                                                                                                ",
   "     !!!!!!!!!!!!!!                                                                                                ",
   "     !!!!!!!!!!!!!!!                                                                                               ",
   "    !!!!!!!!!!!!!!!!!!                                                                                          V   ",
   "  !!!!!!!!!!!!!!!!!!!!!                                                                                            ",
   " !!!!!!!!!!!!!!!!!!!!!!!                                                                                           ",
   " !!!!!!!!!!!!!!!!!!!!!!!                         N       N                       b                           @ #   ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]
];

if (typeof module != "undefined" && module.exports)
	module.exports = POMPEII_LEVEL;
